name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main # change this to the name of your main branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./dist
          cname: paylink.kadergomez.dev
          custom_domain: paylink.kadergomez.dev
          commit_message: Deployed to GitHub Pages
