name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        # uses: actions/deploy-pages@v1
        # with:
        #   token: ${{ secrets.GITHUB_TOKEN }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          # deploy_key: ${{ secrets.DEPLOY_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: paylink.kadergomez.dev
          custom_domain: paylink.kadergomez.dev
          commit_message: Deployed to GitHub Pages
